#include "genome_sequencer.hpp"

#define CATCH_CONFIG_MAIN
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>

#include <string>
#include <vector>

TEST_CASE("Isograd test cases") {
  // clang-format off
  std::vector<std::pair<std::vector<std::string>, std::string>> examples = {
    {{"ACGTT", "AGCTTG", "TAC"}, {"ACGTTCGACAT"}},
    {{"AATGTCATCGCAAA", "AATCCGGCGGATG", "TGTTCGA"}, {"AAACGCTACTGTAATCCGGCGGATGTTCGA"}},
    {{"CGCAAGGTTAAAGTTTC", "AGGACTTT", "AACTGCATAG"}, {"CGCAAGGTTAAAGTTTCAGGATACGTCAA"}},
    {{"GTCA", "CAGGGA", "CTTCAGG"}, {"GTCAGGGACTTC"}},
    {{"CGACGTAAATAGG", "AGGGACACA", "CATACGATT", "ATGCTCTT", "TACTACATG", "ATGATGACTT", "CGTATT"}, {"CGACGTAAATAGGGACACATACGATTCTCGTACATCATGATGACTTATGC"}},
    {{"GTTCTTCGGT", "GGTTAGTATA", "TAACGTCATTC", "ACCCTTACTCT", "CCAACGT", "GTTAGTGGGGGG", "GGGC"}, {"GTTCTTCGGTTAGTATAACGTCATTCTCATTCCCAACGTTAGTGGGGGGC"}},
    {{"GATCG", "TATGC", "AGTCT", "ATGCTCAG", "TGAC"}, {"GATCGTATCTGATGCTCAGT"}},
    {{"CAAGGTCCACTA", "CTGCCGCAAAGAAGC", "AGCTGCTTAGTG", "GCTAGGTAGC", "TAGCACGTCCGCTGCGC", "TGCGCGCTCATGAG", "TAAACGTAGGA", "CTATGCTAAAC", "GGAGTCGACACAGC", "GATGCGACAC"}, {"ATCACCTGGAACTGCCGCAAAGAAGCTGCTTAGTGCTAGGTAGCACGTCCGCTGCGCGCTCATGAGGATGCAAATCGTATCGGAGTCGACACAGCGTAG"}},
    {{"AAAATATTCCGACCA", "AGTTTTTA", "TAAGACCATATTCCACA", "GAGCATACGAGATAAGAC", "TGTGGACCGAGAGCAT", "AGACGAGTGTGGA", "AGCAGAAGCACTAAG", "TAAGCAACACCACCA", "AACTTGCACTGACCA", "GTTCAAGT"}, {"ACCAGCCTTATAAAATTTTTGACACCTTATACCAGAATAGAGCATACGAGAGCCAGGTGTGAGCAGAAGCACTAAGCAACACCACCAGTCACGTTCAAGT"}},
    {{"AGTCT", "ATGCTCAG", "TGAC", "GATCG", "TATGC", "AGTCT", "ATGCTCAG", "TGAC"}, {"TCTGATGCTCAGTGATCGTATCTGATGCTCAGT"}}
  };
  // clang-format on

  auto index = GENERATE(0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
  auto example = examples[index];
  auto input = example.first;
  auto output = example.second;

  REQUIRE(sequence(input) == output);
}
