cc_library(
    name = "genome_sequencer",
    visibility = ["//visibility:public"],
    includes = ["."],
    hdrs = [
        "genome_sequencer.hpp"
    ],
    srcs = [
        "genome_sequencer.cpp"
    ]
)
